Feature/race track
IT-Sadok/VitaliyV pull request #7
Opened 2024-07-11 10:24 UTC by 2Marshall6

2024-07-12 09:44 UTC, sawabond requested changes
Requested changes

2024-07-12 09:44 UTC, sawabond commented on RaceTrack/Tournament/Tournament.cs
> +                    }
This way you wait when all 5 races end. But take a look at this situation:
You've got 4 races that take 30 seconds, and one that takes 4 minutes.
With this implementation your 4 tracks will not be used for 3:30 minutes. You should reconsider the multithreading logic

2024-07-12 09:44 UTC, sawabond commented on RaceTrack/Tournament/Tournament.cs
> +        public Queue<Racer> _winners = new Queue<Racer>();
It should be private field probably

2024-07-12 09:44 UTC, sawabond commented on RaceTrack/Tournament/Tournament.cs
> +        public Action<Racer, Racer, Racer> OnRaceCompleted;
Use property injection or constructor injection - now it's public field

2024-07-12 09:44 UTC, sawabond commented on RaceTrack/Tournament/Tournament.cs
> +        public Action<Racer, Racer, Racer> OnRaceCompleted;
Create a model which will contain 3 Racers because now it's difficult to understand what are these 3 racers

2024-07-12 09:44 UTC, sawabond commented on RaceTrack/Tournament/Tournament.cs
> +        public Queue<Racer> _winners = new Queue<Racer>();
May be for your implementation you will need `ConcurrentQueue` and/or `SemaphoreSlim`

2024-07-12 09:44 UTC, sawabond commented on RaceTrack/DataRacer/Racer.cs
> +        }
SRP violation. Better to create RacerFactory for it

2024-07-12 09:44 UTC, sawabond commented on RaceTrack/Tournament/Tournament.cs
> +        }
It's better to distinguish between `Tournament` entity and `TournamentResult`. Please refactor to make classes more logical

2024-07-14 14:34 UTC, VladMakarenko99 commented on RaceTrack/Tournament/RacerFactory.cs
> +    public class RacerFactory
Being you, I would make this class static with static method

2024-07-14 14:36 UTC, VladMakarenko99 commented on RaceTrack/Tournament/Tournament.cs
> +        public async Task<Racer> GetWinnerAsync(Racer racer1, Racer racer2)
This method is used only inside of it's class. You can make it private

2024-07-14 14:37 UTC, VladMakarenko99 commented on RaceTrack/Tournament/Tournament.cs
> +        public async Task RaceAsync(Racer racer1, Racer racer2)
The same with this method

2024-07-14 14:38 UTC, VladMakarenko99 commented on RaceTrack/Tournament/Tournament.cs
> +    public class TournamentResult
Also there is some inconsistency, because file named `Tournament` and class inside of it - `TournamentResult`

2024-07-14 14:38 UTC, VladMakarenko99 reviewed
Nice job, left just few comments

2024-07-16 08:45 UTC, sawabond commented on RaceTrack/PresentationLayer/Program.cs
> +        };
Better make a static method in Main and pass this method reference here. will look cleaner

2024-07-16 08:48 UTC, sawabond reviewed
Good job need some minor code fixes

2024-07-16 08:48 UTC, sawabond commented on RaceTrack/Tournament/RacersModel.cs
> +        public Racer Winner { get; set; }
Make `init` or record because after creating a model everybody can change the Winner

2024-07-16 08:48 UTC, sawabond commented on RaceTrack/Tournament/Tournament.cs
> +        }
Why do yyou check racers cound 2 times in loop

2024-07-23 21:06 UTC, sawabond approved these changes
Approved

2024-09-03 20:17 UTC, merged